Update application.yml with suggestions from TOC issue #1461
cncf/sandbox pull request #305
Opened 2024-10-27 20:15 UTC by angellk

Updated per @edrob999's suggestions and to address the suggestions brought up by @TheFoxAtWork 

Outstanding is reviewing and further clarifying the language to align with the GTR/DTR questions.

xref: https://github.com/cncf/toc/issues/1461

2024-10-28 02:51 UTC, kevin-wangzefeng approved these changes
LGTM, thanks

2024-10-28 12:06 UTC, TheFoxAtWork approved these changes
Lgtm thank you!!!

2024-10-28 13:28 UTC, dims approved these changes
LGTM

2024-10-28 13:29 UTC, merged

2024-10-29 01:41 UTC, TheFoxAtWork requested changes
Incorporating "answer"

2024-10-29 01:41 UTC, TheFoxAtWork commented on .github/ISSUE_TEMPLATE/application.yml
> +    description: Please list any people who are part of CNCF leadership (TOC, TAGS, etc.) who are familiar with, and can questions about your project.
```suggestion
    description: Please list any people who are part of CNCF leadership (TOC, TAGS, etc.) who are familiar with, and can answer questions about your project.
```

2024-11-02 03:42 UTC, angellk reviewed
lgtm

2025-05-21 03:28 UTC, johnaAr555 approved these changes